name: nates_production_pro
description: Nate's Fine Foods blancher and production management app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  vibration: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/nates_logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/nates_logo.png"
  adaptive_icon_background: "#06121F"
  adaptive_icon_foreground: "assets/nates_logo.png"
